### ISSUE TITLE
Not working with Rails 3.2.5 and Thin

### ISSUE THREAD

**Issue by RKushnir** [tye/rubyception#7]
> rails -v
> _Rails 3.2.5_
> 
> thin -v
> _thin 1.3.1 codename Triple Espresso_

In development `thin` just says 'Exiting' immediately after starting. In `development.log` I see only:

```
Could not log "sql.active_record" event. NoMethodError: undefined method `<<' for nil:NilClass
```

**Comment by tye** [comment]
Thanks for the bug report. I'll be looking at the issue soon & releasing a fix.

**Comment by RKushnir** [comment]
Cool, thanks. Curious to see it in action.

**Comment by gudata** [comment]
when using this gem with Rails 3.2.(6,7) + thin 1.4.1 thin just prints exiting... and quits

**Comment by omenking** [comment]
I was able to replicate the error with rails 3.2.5 using thin.

This issue may have been related to compass issue we solved in version 0.0.3.
Would you go ahead and update your gem, and see if the problem is resolved?

**Comment by RKushnir** [comment]
Installed the latest version from git and still the same.

**Comment by firedev** [comment]
Same thing - thin just exits

**Comment by tye** [comment]
Issue confirmed, it definitely doesn't work with thin.
Ill let you know as soon as this is fixed.

**Comment by tye** [comment]
Just pushed 0.1.0, let me know if there problem is still occurring for you

**Comment by firedev** [comment]
Works fine now, thanks!

**Comment by RKushnir** [comment]
Works for me either, thanks!

**Comment by OneDivZero** [comment]
Having the same problem with mongrel. Have not yet confirmed if it only occures on server-startup or randomly. Maybe something get's to early initialized ?
